name: "Kubecost cost prediction"
author: "Michael Dresser (Kubecost)"
description: "Predict the cost impact of code changes to K8s object specs using Kubecost"
inputs:
  path:
    decription: 'The specific path of a workload or directory of workloads to predict'
    required: true
  kubecost_api_path:
    description: 'URL of the Kubecost API. Example: https://kubecost.example.com:9090/model'
    required: false
  log_level:
    description: "The log level of the action code"
    required: false
    default: "info"
  outputs:
    PREDICTION_TABLE:
      description: 'The ASCII table-formatted prediction'

runs:
  using: 'docker'
  image: "docker://gcr.io/kubecost1/cost-prediction-action:0.1.0"
  env:
    PREDICTION_PATH: ${{ inputs.path }}
    LOG_LEVEL: ${{ inputs.log_level }}
    KUBECOST_API_PATH: ${{ inputs.kubecost_api_path }}
branding:
  color: green
  icon: dollar-sign
