name: TEST PR workflow
on:
  pull_request:

jobs:
  predict-pr-noapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: ./

      - name: Checkout kubecost/github-actions
        uses: actions/checkout@v2
        with:
          repository: kubecost/github-actions
          token: ${{ secrets.CPA_ACTIONS_PAT }}
          path: ./github-actions

      - name: Run predict on test files
        id: prediction
        uses: ./
        with:
          log_level: "debug"
          path: ./test

      - name: Output prediction
        run: |
          echo "${{ steps.prediction.outputs.PREDICTION_TABLE }}"

      - name: Find existing PR comment
        uses: ./github-actions/find-comment
        id: find-comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- kubecost-prediction-results -->'

      - name: Create or update PR comment with prediction results
        uses: ./github-actions/create-or-update-comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            <!-- kubecost-prediction-results -->

            ## Kubecost's total cost prediction for K8s manifests in `./test`

            ```
            ${{ steps.prediction.outputs.PREDICTION_TABLE }}
            ```
