name: TEST Predict the KC Helm chart
on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  predict-cost-helm:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout latest Action version
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: ./action
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
        with:
          version: v4.2.3

      - name: Template chart
        run: |
          helm repo add kubecost https://kubecost.github.io/kubecost
          helm template kubecost kubecost/kubecost --version 3.3.0 -n kubecost --skip-tests > ./templated.yaml

      - name: Predict cost of templated chart
        id: prediction
        uses: ./action
        with:
          path:
            ./templated.yaml

      - name: Output prediction
        env:
          PREDICTION_TABLE: ${{ steps.prediction.outputs.PREDICTION_TABLE }}
        run: |
          printf '%s\n' "$PREDICTION_TABLE"
