name: TEST Predict Action

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  predict-cost:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: ./
          persist-credentials: false

      - name: local action with raw yaml
        id: raw-prediction
        uses: ./
        with:
          log_level: "warn"
          path: ./test

      - name: output raw yaml prediction
        env:
          PREDICTION_TABLE: ${{ steps.raw-prediction.outputs.PREDICTION_TABLE }}
        run: |
          printf '%s\n' "$PREDICTION_TABLE"
